# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: pwd 1
        run: pwd
      - name: change dir
        run: cd $GITHUB_WORKSPACE
      - name: pwd 2
        run: pwd
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build -x test --stacktrace
      - name: pwd 3
        run: pwd
      - name: exit git folder
        run: cd ..
      - name: pwd 4
        run: pwd
      - name: install codacy
        run: cd .. && curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz
      - name: install codacy 2
        run: cd .. && cd codacy-analysis-cli-* && sudo make install
      - name: run codacy
        run: cd .. && codacy-analysis-cli analyze --tool spotbugs --upload --allow-network --max-allowed-issues 999999 --commit-uuid $GITHUB_SHA
